services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=dochub'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3308:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: